#!/usr/bin/env bash

set -e

: "${1:?Missing executable name}"
: "${1:?Missing debug flags}"

pwd=`dirname $0`
filename=`basename $1`
debugflags=$2

./my-progs/build debug

gdb \
  -ex "set args --debug-flags=$debugflags configs/deprecated/example/se.py --cmd=$pwd/$filename -n 1 --mem-type SimpleMemory --caches --l2cache --cpu-type O3CPU --maxinsts=1000000" \
  build/X86/gem5.debug
